import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from naw_crop import crop

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "crt_2nd_ed.json")

CROPS = [
    (0.760, 0.540, 0.920, 0.680, "zz_crt_left", 270, 1.3),
    (0.760, 0.600, 0.920, 0.800, "zz_crt_full", 270, 1.15),
    (0.760, 0.760, 0.920, 0.880, "zz_crt_right", 270, 1.3),
]

COLS = ["1:5", "1:4", "1:3", "1:2", "1:1", "2:1", "3:1", "4:1", "5:1", "6:1"]

TABLE = {
    1: ["AE", "Ar", "Ar", "Dr", "Dr", "Dr", "DE", "DE", "DE", "DE"],
    2: ["AE", "AE", "Ar", "Ar", "Dr", "Dr", "Dr", "DE", "DE", "DE"],
    3: ["AE", "AE", "AE", "Ar", "Dr", "Dr", "Dr", "Dr", "DE", "DE"],
    4: ["AE", "AE", "AE", "Ar", "Ar", "Dr", "Dr", "Dr", "DE", "DE"],
    5: ["AE", "AE", "AE", "Ar", "Ar", "EX", "Dr", "EX", "EX", "DE"],
    6: ["AE", "AE", "AE", "AE", "Ar", "Ar", "EX", "EX", "EX", "DE"],
}


def regen():
    for x0, y0, x1, y1, name, rot, sc in CROPS:
        crop("ed2scan", 5, x0, y0, x1, y1, name, rotate=rot, scale=sc)


def build():
    doc = {
        "produced_by": "PREP-5 collation, games/napoleon-at-waterloo/ingest/naw_crt_extract.py",
        "read_on": "2026-08-14",
        "edition": "SPI Napoleon at Waterloo, SECOND EDITION, copyright 1971",
        "authority": "PRIMARY. Machine-readable capture of the Combat Resolution Table printed on "
        "the folio map sheet (page 5). The CRT had been transcribed cell by cell in PREP-1/PREP-2 "
        "but only ever into prose in RULEBOOK_VERIFIED.md; nothing downstream could consume it. "
        "This file is that transcription made machine-readable AND independently re-read off the "
        "print a fourth time during PREP-5 collation.",
        "source": {
            "file": "Napoleon at Waterloo (2nd Ed)/NapoleonatWaterloo.pdf",
            "page": 5,
            "render": "embedded page image at native 6952x5171, no resample",
            "block": "Combat Resolution Table, French-side copy, printed at 270 degrees",
            "note": "The sheet prints TWO copies, one per player; PREP-1 read both and they agree "
            "cell for cell.",
        },
        "verification": {
            "method": "all 60 cells re-read BY EYE off three rotated crops regenerated by this "
            "script, then compared against RULEBOOK_VERIFIED.md section 3",
            "cells_checked": 60,
            "cells_agreeing": 60,
            "verdict": "EXACT MATCH. The prose transcription is confirmed; no cell changed.",
            "crops": [c[4] for c in CROPS],
            "crop_coverage": {
                "zz_crt_right": "columns 1:5, 1:4, 1:3 and part of 1:2",
                "zz_crt_full": "columns 1:3 (partial), 1:2, 1:1, 2:1, 3:1, 4:1",
                "zz_crt_left": "columns 3:1, 4:1, 5:1, 6:1",
            },
            "caveat": "This is a fourth reading of the SAME printed artefact, not a new witness. "
            "It defends against transcription drift between the doc and the data, not against a "
            "misprint in the folio itself.",
        },
        "odds_columns": COLS,
        "die": [1, 2, 3, 4, 5, 6],
        "orientation": "table[die][odds_column] -> result code",
        "table": {str(k): dict(zip(COLS, v)) for k, v in TABLE.items()},
        "result_codes": {
            "AE": "Attacker Eliminated",
            "Ar": "Attacker Retreats one hex",
            "Dr": "Defender Retreats",
            "DE": "Defender Eliminated",
            "EX": "Exchange - the defender is eliminated and the attacker suffers a loss AT LEAST "
            "EQUAL in Strength Points, made up only from units directly involved in that attack",
        },
        "result_code_note": "PREP-2 E04: the 3rd Edition renames these Ae/Ee/De. It is a RENAME, "
        "not a rules change - map them, never branch on them.",
        "clamp_printed_verbatim": "Attacks executed at worse than “1 to 5” are treated as "
        "“1 to 5”; attacks executed at greater than “6 to 1” are treated as "
        "“6 to 1”.",
        "clamp_read": "by-eye, footnote visible in zz_crt_full and zz_crt_left",
        "odds_rounding": {
            "rule": "Attacker's total Combat Strength vs defender's total, expressed as a ratio and "
            "ROUNDED OFF IN FAVOUR OF THE DEFENDER",
            "source": "folio p.1 Combat section",
            "edition_diff": "E05 - identical in both editions",
        },
        "consumers": [
            "the printed Examples of Attacks (folio p.2) are the validation corpus - every printed "
            "example must resolve to its printed odds and result against this table",
            "PREP-7 decode plan / coverage matrix",
        ],
    }
    json.dump(doc, open(OUT, "w"), indent=1)
    print(OUT, "written", len(TABLE) * len(COLS), "cells")


if __name__ == "__main__":
    if "--regen" in sys.argv:
        regen()
    build()
